# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.


name: Dev Workflow - Test and check
on:
  push:
    branches: [ "dev2" ]

permissions:
  contents: read

jobs:
  R-CMD-check:
    name: R CMD Check
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo for workflow access
        uses: actions/checkout@v4

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Set up R environment
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Set up dependencies (general)
        uses: r-lib/actions/setup-r-dependencies@v2
        env:
          _R_CHECK_FORCE_SUGGESTS: false
          _R_CHECK_RD_XREFS: false
        with:
          dependencies: '"hard"' # do not use suggested dependencies
          install-pandoc: false
          extra-packages: |
            any::rcmdcheck
            any::testthat
            any::rlang
            any::R.utils
            any::knitr
            any::rmarkdown
            any::qs
            any::sp
            any::stars
            any::raster
            any::sf
            any::scattermore
            any::exactextractr
            any::RTriangle
            any::geometry
            any::qs
            any::future.apply
            any::Biobase
            any::chihaya
            any::DelayedArray
            any::DelayedMatrixStats
            any::HDF5Array
            any::plotly
            any::rgl
            any::rhdf5
            any::S4Vectors
            any::ScaledMatrix
            any::XML
            any::Seurat
            any::SeuratObject
            any::SingleCellExperiment
            any::SpatialExperiment
            any::STexampleData
            any::SummarizedExperiment
            github::drieslab/GiottoData
            
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: setup giotto_env
        shell: Rscript {0}
        run: |
          path_to_python <- reticulate::virtualenv_create(
            envname = "giotto_env",
            python = Sys.which("python"), # placed on PATH by the setup-python action
            packages = c(
              "pandas==1.5.1",
              "networkx==2.8.8",
              "python-igraph==0.10.2",
              "leidenalg==0.9.0", 
              "python-louvain==0.16",
              "scikit-learn==1.1.3",
              "scipy==1.13.0",
              "scanpy"
             )
           )
              
           writeLines(sprintf("RETICULATE_PYTHON=%s", path_to_python),
                      Sys.getenv("GITHUB_ENV"))

      - name: Run R CMD check
        uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          error-on: '"error"' # workflow errors on error only, can change to include warnings

      # show testthat output for ease of access
      - name: Show testthat output
        if: always()
        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash



